server:
  port: 8081
spring:
  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
  datasource:
    url: jdbc:mysql://localhost:3306/graduation?useAffectedRows=true&useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT&useAffectedRows=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
mybatis:
  type-aliases-package: com.clown.design.entity
  mapper-locations: classpath:mapper/*.xml